server:
  port: 40923

spring:
  application:
    name: shopping-service
  # DataSource Config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.4.93:3306/db_sc?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
  #mvc自定义路径配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #redis缓存
  redis:
    host: 47.94.4.93 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  #spring data mongodb
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: dbdj1201 # mongodb的连接的数据库
      username: root
      password: root
  #spring data elasticsearch
  elasticsearch:
    rest:
      uris: 47.94.4.93:9200
  #spring rabbitmq
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /test # rabbitmq的虚拟host
    username: rabbitmq # rabbitmq的用户名
    password: rabbitmq # rabbitmq的密码
#  freemarker:
#    expose-spring-macro-helpers:
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
#配置自定义redis key
#redis:
#  key:
#    prefix:
#      authCode: "dbdj1201:sc:authCode:"
#    expire:
#      authCode: 1800

#jwt 参数配置
#jwt:
#  #密钥
#  secret: dbdj1201&yz1201
#  #有效时间
#  expiration: 180000
#  #token header
#  tokenHeader: Authorization
#  tokenHead:  dbdj1201